project_name: opg-infra-costs

env_files:
  github_token: ${{ secrets.GITHUB_TOKEN }}

release:
  github:
    owner: charlesmmarshall
    name: opg-infra-costs

builds:
  - binary: opg-infra-costs
    id: opg-infra-costs
    main: ./main.go
    goos:
      - freebsd
      - openbsd
      - solaris
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
