name: Release on tag
on:
  push:
      tags:
        - "v*.*.*"
      branches:
        - "!*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - name: Checkout code into the go module directory
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
